// Bank soal contoh (mode demo) — dipakai otomatis kalau NEXT_PUBLIC_SHEETY_BASE_URL
// belum diisi di .env.local. Begitu Sheety sudah tersambung ke Google Sheet,
// app akan otomatis pakai soal dari Sheet, bukan dari file ini lagi.
// Struktur kolom di Sheet "SOAL" harus sama persis dengan field di bawah ini.

const soalFallback = [
  {
    id: 1,
    kode: 'SOAL1',
    kategori: 'TWK',
    soal: 'Pancasila sebagai dasar negara memiliki kedudukan sebagai sumber dari segala sumber hukum. Hal ini tercantum dalam ketetapan MPR nomor...',
    pilihanA: 'Tap MPR No. I/MPR/2003',
    pilihanB: 'Tap MPR No. III/MPR/2000',
    pilihanC: 'Tap MPR No. V/MPR/1999',
    pilihanD: 'Tap MPR No. II/MPR/2001',
    pilihanE: 'Tap MPR No. IV/MPR/1999',
    kunci: 'B',
  },
  {
    id: 2,
    kode: 'SOAL1',
    kategori: 'TWK',
    soal: 'Semboyan "Bhinneka Tunggal Ika" pertama kali termuat dalam kitab...',
    pilihanA: 'Negarakertagama',
    pilihanB: 'Sutasoma',
    pilihanC: 'Pararaton',
    pilihanD: 'Arjunawiwaha',
    pilihanE: 'Smaradahana',
    kunci: 'B',
  },
  {
    id: 3,
    kode: 'SOAL1',
    kategori: 'TIU',
    soal: 'Jika semua pegawai teladan rajin bekerja, dan Budi adalah pegawai teladan, maka...',
    pilihanA: 'Budi mungkin rajin bekerja',
    pilihanB: 'Budi rajin bekerja',
    pilihanC: 'Budi tidak rajin bekerja',
    pilihanD: 'Semua pegawai adalah Budi',
    pilihanE: 'Tidak dapat disimpulkan',
    kunci: 'B',
  },
  {
    id: 4,
    kode: 'SOAL1',
    kategori: 'TIU',
    soal: 'Diketahui barisan bilangan 3, 7, 15, 31, 63, ... Bilangan berikutnya adalah...',
    pilihanA: '95',
    pilihanB: '111',
    pilihanC: '119',
    pilihanD: '127',
    pilihanE: '135',
    kunci: 'D',
  },
  {
    id: 5,
    kode: 'SOAL1',
    kategori: 'TIU',
    soal: 'ANTONIM kata "KONTRIBUSI" adalah...',
    pilihanA: 'Sumbangan',
    pilihanB: 'Partisipasi',
    pilihanC: 'Pengabaian',
    pilihanD: 'Bantuan',
    pilihanE: 'Peran serta',
    kunci: 'C',
  },
  {
    id: 6,
    kode: 'SOAL1',
    kategori: 'TIU',
    soal: 'Sebuah mobil menempuh jarak 240 km dalam waktu 3 jam. Berapa waktu yang dibutuhkan untuk menempuh 400 km dengan kecepatan sama?',
    pilihanA: '4 jam',
    pilihanB: '4,5 jam',
    pilihanC: '5 jam',
    pilihanD: '5,5 jam',
    pilihanE: '6 jam',
    kunci: 'C',
  },
  {
    id: 7,
    kode: 'SOAL1',
    kategori: 'TIU',
    soal: 'PADI : BERAS = KAPAS : ...',
    pilihanA: 'Kain',
    pilihanB: 'Benang',
    pilihanC: 'Baju',
    pilihanD: 'Serat',
    pilihanE: 'Tekstil',
    kunci: 'B',
  },
  {
    id: 8,
    kode: 'SOAL1',
    kategori: 'TKP',
    soal: 'Atasan Anda memberikan tugas mendadak yang harus selesai hari itu juga, padahal Anda sudah punya rencana lain di luar kantor. Sikap Anda...',
    pilihanA: 'Menolak karena sudah ada janji pribadi',
    pilihanB: 'Mengerjakan tugas seadanya agar cepat selesai',
    pilihanC: 'Menyelesaikan tugas terlebih dahulu dan menyesuaikan rencana pribadi',
    pilihanD: 'Meminta rekan kerja mengerjakan tugas tersebut',
    pilihanE: 'Mengabaikan tugas karena bukan prioritas Anda',
    kunci: 'C',
  },
  {
    id: 9,
    kode: 'SOAL1',
    kategori: 'TKP',
    soal: 'Anda menemukan kesalahan pada laporan yang sudah diserahkan rekan satu tim ke pimpinan. Yang Anda lakukan...',
    pilihanA: 'Diam saja karena bukan tanggung jawab Anda',
    pilihanB: 'Langsung melapor ke pimpinan tanpa memberi tahu rekan',
    pilihanC: 'Membicarakan langsung ke rekan tersebut untuk diperbaiki bersama',
    pilihanD: 'Membiarkan dan membicarakan di belakang',
    pilihanE: 'Memperbaiki sendiri tanpa sepengetahuan siapa pun',
    kunci: 'C',
  },
  {
    id: 10,
    kode: 'SOAL1',
    kategori: 'TKP',
    soal: 'Instansi Anda menerapkan sistem kerja baru yang belum Anda pahami sepenuhnya. Sikap Anda...',
    pilihanA: 'Menolak menggunakan sistem baru tersebut',
    pilihanB: 'Mempelajari sistem baru secara mandiri dan bertanya jika perlu',
    pilihanC: 'Menunggu rekan lain menguasainya lebih dulu',
    pilihanD: 'Tetap memakai cara lama karena lebih familiar',
    pilihanE: 'Mengeluh kepada atasan agar sistem lama dipertahankan',
    kunci: 'B',
  },
];

export default soalFallback;
